### ISSUE TITLE
Could the bundle work with map.apps 4.11.1?

### ISSUE THREAD

**Issue by alaacs** [conterra/mapapps-magnifier#2]
While upgrading a project from line 3 to line 4, I want to upgrade the old magnifier bundle to this bundle instead.
The upgrade target is map.apps 4.11.1, is there a reason for this bundle to be supported in 4.11.1?

**Comment by sholtkamp** [comment]
Hello,
the magnifier as provided by this bundle requires the ArcGIS Maps SDK for JavaScript Version 4.19 or later (see: [Documentation](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-Magnifier.html)).
Therefore, the minimum required version of map.apps to use this bundle ist 4.12
